apiVersion: v1
kind: Service
metadata:
  name: vue-frontend-emergency-ward-panels-service
spec:
  selector:
    app: vue-frontend-emergency-ward-panels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

