repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: keycloak-operator
    url: https://kbumsik.io/keycloak-kubernetes/
  - name: kubernetes-dashboard 
    url: https://kubernetes.github.io/dashboard/


releases:
  - name: sancommitto
    chart: ./
    namespace: default
    needs:
      - cert-manager/cert-manager
      - cert-manager/trust-manager
    values:
      - ./values.yaml

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    # Without waiting, sancommitto exceeds context deadline
    wait: true
    set:
      - name: crds.enabled
        value: true

  - name: trust-manager
    chart: jetstack/trust-manager
    namespace: cert-manager
    needs:
      # trust-manager needs the CRDs in cert-manager
      - cert-manager/cert-manager
    # Without waiting, sancommitto exceeds context deadline
    wait: true
    set:
      - name: secretTargets.enabled
        value: true
        # The option --set secretTargets.enabled=true is required to write the trust bundle to a secret
        # Vaffanculo Keycloak che non supporta le ConfigMap per i trust bundles
        # This is can be dangerous, but it took me two days, without it it doesn't work
      - name: secretTargets.authorizedSecretsAll
        value: true

  - name: kubernetes-dashboard 
    chart: kubernetes-dashboard/kubernetes-dashboard 
    namespace: kubernetes-dashboard
