apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
  labels:
    app: react-frontend

spec:
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: ghcr.io/git-commit-therapy/react-frontend:sample
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred

