apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend-deployment
  labels:
    app: vue-frontend

spec:
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
        - name: vue-frontend
          image: ghcr.io/git-commit-therapy/vue-frontend:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred

