apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy-service
spec:
  type: LoadBalancer
  selector:
    app: envoy-proxy
  ports:
  - name: envoy-proxy-service-port
    protocol: TCP
    port: 80
    targetPort: envoy-port
