apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-certificate
  namespace: cert-manager
spec:
  secretName: root-key-pair-secret
  isCA: true
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  commonName: "sancommitto.com"

