apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: root-trust-bundle  # The bundle name will also be used for the target
spec:
  sources:
  # Include a bundle of publicly trusted certificates which can be
  # used to validate most TLS certificates on the internet, such as
  # those issued by Let's Encrypt, Google, Amazon and others.
  - useDefaultCAs: true

  # A Secret in the "trust" namespace; see "Trust Namespace" below for further details
  - secret:
      name: "root-key-pair-secret"
      key: "tls.crt"

  target:
    # Sync the bundle to a ConfigMap and a Secret, both called `root-trust-bundle` in every namespace
    # # All ConfigMaps will include a PEM-formatted bundle, here named "root-certs.pem"
    # and in this case we also request binary formatted bundles in JKS and PKCS#12 formats,
    # here named "bundle.jks" and "bundle.p12".
    configMap:
      key: "root-certs.pem"
    # Keycloak requires a secret to provide trust stores
    secret:
      key: "root-certs.pem"
    additionalFormats:
      jks:
        key: "bundle.jks"
      pkcs12:
        key: "bundle.p12"
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: "default"
      #     linkerd.io/inject: "enabled"
      #
