apiVersion: v1
kind: Service
metadata:
  name: java-email-sender-service
spec:
  selector:
    app: java-emergency-ward-panels
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.email_sender.server_port }}

