apiVersion: v1
kind: Service
metadata:
  name: java-emergency-ward-panels-service
spec:
  selector:
    app: java-emergency-ward-panels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10000

